version: '3'
services:
  api:
    image: app
    build: ./app
    container_name: app_api
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: api run --port 5000
    environment:
      TZ: America/Lima
    ports:
      - "5000:5000"